# NOTE: this example targets the master branch of i3status-rust.
#
# For latest stable version, refer to
# https://github.com/greshake/i3status-rust/blob/v0.22.0/examples/config.toml

theme = "native"
icons = "awesome"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
interval = 5 
format = "{percentage}"
full_threshold = 100
warning = 30
critical = 10

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "sound"
format = "{volume}"

[[block]]
block = "time"
format = "%d/%m %R"
timezone = "Brazil/East"
interval = 60
locale = "pt_BR"
